- name: The yourbtc.link installer
  hosts: all

  pre_tasks:
    - name: Update system
      become: true
      apt:
        update_cache: yes
        upgrade: dist
      tags:
        - init

  roles:
    - role: fooock.bitcoind
      vars:
        bitcoin_network: regtest
        bitcoin_zmq_host: 192.168.56.4
        bitcoin_rpc_bind: 192.168.56.4
        bitcoin_rpc_allow_ip: 192.168.56.5
      tags:
        - bitcoin
