- name: The yourbtc.link installer
  hosts: all

  pre_tasks:
    - name: Update system
      become: true
      apt:
        update_cache: yes
        upgrade: dist
      tags:
        - init

  tasks:
    - name: Install Lighting Network Daemon
      vars:
        lnd_network: regtest
        lnd_bitcoind_local: false
        lnd_bitcoind_rpc_host: 192.168.56.4
        lnd_bitcoind_rpc_user: yourbtc
        lnd_bitcoind_rpc_password: yourbtc
      import_role:
        name: ../../ansible/lnd-role
      tags:
        - lnd
