---
- name: "Ensure group '{{ lnd_group }}' exists"
  ansible.builtin.group:
    name: "{{ lnd_group }}"
    state: present

- name: "Ensure user '{{ lnd_user }}' with a primary group of '{{ lnd_group }}' exists"
  ansible.builtin.user:
    name: "{{ lnd_user }}"
    group: "{{ lnd_group }}"
    state: present
    password: "*"

- name: "Download LND v{{ lnd_version }} into '/tmp/lnd-{{ lnd_arch }}-{{ lnd_version }}.tar.gz'"
  ansible.builtin.get_url:
    url: https://github.com/lightningnetwork/lnd/releases/download/v{{ lnd_version }}/lnd-{{ lnd_arch }}-v{{ lnd_version }}.tar.gz
    dest: /tmp/lnd-{{ lnd_arch }}-{{ lnd_version }}.tar.gz
    checksum: sha256:https://github.com/lightningnetwork/lnd/releases/download/v{{ lnd_version }}/manifest-v{{ lnd_version }}.txt
    http_agent: yourbtc-ansible

- name: "Ensure '/usr/local/lnd-{{ lnd_version }}' directory exists"
  file:
    path: /usr/local/lnd-{{ lnd_version }}
    state: directory

- name: "Unpack 'lnd-{{ lnd_arch }}-{{ lnd_version }}.tar.gz' into '/usr/local/lnd-{{ lnd_version }}'"
  ansible.builtin.unarchive:
    src: /tmp/lnd-{{ lnd_arch }}-{{ lnd_version }}.tar.gz
    dest: /usr/local/lnd-{{ lnd_version }}
    remote_src: yes
    owner: "{{ lnd_user }}"
    group: "{{ lnd_group }}"
    extra_opts:
      - --strip-components=1
