---
- name: "Ensure 'lnd-{{ lnd_network }}.service' systemd unit is restarted"
  ansible.builtin.systemd:
    name: lnd-{{ lnd_network }}.service
    state: restarted
  tags:
    # This is to avoid trying to execute this test by Molecule
    # when using the docker driver since it doesn't use systemd
    - notest
