# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "bitcoind" do |bitcoind|
    bitcoind.vm.box = "ubuntu/focal64"
    bitcoind.vm.network "private_network", ip: "192.168.56.4"
    bitcoind.vm.hostname = "yourbtc-bitcoind"

    bitcoind.vm.provision "ansible" do |ansible|
      ansible.playbook = "btc-playbook.yml"
      ansible.become = true
    end
  end

  config.vm.define "lnd" do |lnd|
    lnd.vm.box = "ubuntu/focal64"
    lnd.vm.network "private_network", ip: "192.168.56.5"
    lnd.vm.hostname = "yourbtc-lnd"

    lnd.vm.provision "ansible" do |ansible|
      ansible.playbook = "lnd-playbook.yml"
      ansible.become = true
    end
  end

end
