---
- name: "Ensure group '{{ bitcoin_group }}' exists"
  ansible.builtin.group:
    name: "{{ bitcoin_group }}"
    state: present

- name: "Ensure user '{{ bitcoin_user }}' with a primary group of '{{ bitcoin_group }}' exists"
  ansible.builtin.user:
    name: "{{ bitcoin_user }}"
    group: "{{ bitcoin_group }}"
    state: present
    password: "*"

- name: "Download Bitcoin Core v{{ bitcoin_version }} into '/tmp/bitcoin-core-{{ bitcoin_version }}-{{ bitcoin_arch }}.tar.gz'"
  ansible.builtin.get_url:
    url: https://bitcoincore.org/bin/bitcoin-core-{{ bitcoin_version }}/bitcoin-{{ bitcoin_version }}-{{ bitcoin_arch }}.tar.gz
    dest: /tmp/bitcoin-core-{{ bitcoin_version }}-{{ bitcoin_arch }}.tar.gz
    checksum: sha256:https://bitcoincore.org/bin/bitcoin-core-{{ bitcoin_version }}/SHA256SUMS
    http_agent: yourbtc-ansible

- name: "Ensure '/usr/local/bitcoin-core-{{ bitcoin_version }}-{{ bitcoin_arch }}' directory exists"
  ansible.builtin.file:
    path: /usr/local/bitcoin-core-{{ bitcoin_version }}
    state: directory

- name: "Unpack 'bitcoin-core-{{ bitcoin_version }}-{{ bitcoin_arch }}.tar.gz' into '/usr/local/bitcoin-core-{{ bitcoin_version }}'"
  ansible.builtin.unarchive:
    src: /tmp/bitcoin-core-{{ bitcoin_version }}-{{ bitcoin_arch }}.tar.gz
    dest: /usr/local/bitcoin-core-{{ bitcoin_version }}
    remote_src: yes
    owner: "{{ bitcoin_user }}"
    group: "{{ bitcoin_group }}"
    extra_opts:
      - --strip-components=1

- name: "Copy Bitcoin systemd file in '/lib/systemd/system/bitcoind-{{ bitcoin_network }}.service'"
  ansible.builtin.template:
    src: bitcoind.service.j2
    dest: /lib/systemd/system/bitcoind-{{ bitcoin_network }}.service
  notify:
    - "Ensure 'bitcoind-{{ bitcoin_network }}.service' systemd unit is restarted"

- name: "Ensure Bitcoin configuration directory '/etc/bitcoin/bitcoind-{{ bitcoin_network }}' exists"
  ansible.builtin.file:
    path: /etc/bitcoin/bitcoind-{{ bitcoin_network }}
    state: directory
    owner: "{{ bitcoin_user }}"
    group: "{{ bitcoin_group }}"
    mode: 0710

- name: "Copy bitcoin.conf file into '/etc/bitcoin/bitcoind-{{ bitcoin_network }}'"
  ansible.builtin.template:
    src: bitcoin.conf.j2
    dest: /etc/bitcoin/bitcoind-{{ bitcoin_network }}/bitcoin.conf
  become_user: "{{ bitcoin_user }}"
  become: true
  notify:
    - "Ensure 'bitcoind-{{ bitcoin_network }}.service' systemd unit is restarted"

- name: "Ensure Bitcoin data directory '{{ bitcoin_data_dir }}' exists"
  ansible.builtin.file:
    path: "{{ bitcoin_data_dir }}"
    state: directory

- name: "Ensure Bitcoin data directory '{{ bitcoin_data_dir }}' uses the correct permissions"
  ansible.builtin.file:
    path: "{{ bitcoin_data_dir }}"
    state: directory
    owner: "{{ bitcoin_user }}"
    group: "{{ bitcoin_group }}"
    mode: 0750

- name: "Ensure 'bitcoind-{{ bitcoin_network }}.service' systemd unit is enabled and started"
  ansible.builtin.systemd:
    name: bitcoind-{{ bitcoin_network }}.service
    daemon_reload: yes
    enabled: true
    state: started
