---
- name: "Download Bitcoin Core v{{ bitcoin_version }} into /tmp/bitcoin-core-{{ bitcoin_version }}-{{ bitcoin_arch }}.tar.gz"
  ansible.builtin.get_url:
    url: "https://bitcoincore.org/bin/bitcoin-core-{{ bitcoin_version }}/bitcoin-{{ bitcoin_version }}-{{ bitcoin_arch }}.tar.gz"
    dest: /tmp/bitcoin-core-{{ bitcoin_version }}-{{ bitcoin_arch }}.tar.gz
    checksum: sha256:https://bitcoincore.org/bin/bitcoin-core-{{ bitcoin_version }}/SHA256SUMS
    http_agent: yourbtc-ansible

- name: "Ensure /usr/local/bitcoin-core-{{ bitcoin_version }}-{{ bitcoin_arch }} directory exists"
  file:
    path: /usr/local/bitcoin-core-{{ bitcoin_version }}-{{ bitcoin_arch }}
    state: directory

- name: "Unpacks bitcoin-core-{{ bitcoin_version }}-{{ bitcoin_arch }}.tar.gz into /usr/local/bitcoin-core-{{ bitcoin_version }}-{{ bitcoin_arch }}"
  ansible.builtin.unarchive:
    src: "/tmp/bitcoin-core-{{ bitcoin_version }}-{{ bitcoin_arch }}.tar.gz"
    dest: "/usr/local/bitcoin-core-{{ bitcoin_version }}-{{ bitcoin_arch }}"
    remote_src: yes
