install:
	ansible-playbook -i localhost, --connection=local playbook.yml

install-bitcoin:
	ansible-playbook -i localhost, --connection=local playbook.yml --tags bitcoin

install-lnd:
	ansible-playbook -i localhost, --connection=local playbook.yml --tags lnd
