- name: The yourbtc.link installer
  hosts: all

  pre_tasks:
    # Always update the base system
    - name: Update system
      apt:
        update_cache: yes
        upgrade: dist
      tags:
        - init

  tasks:
    - name: Install Bitcoin Core client
      import_role:
        name: bitcoin-role
      tags:
        - bitcoin
