---
on:
  push:
    paths:
      - '.github/workflows/ansible.yml'
      - 'yourbtc-ansible/**'

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.9 ]
        projects:
          - bitcoin-role

    steps:
      - uses: actions/checkout@v2
      - name: Check Ansible role syntax
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          playbook: playbook.yml
          directory: ./yourbtc-ansible
          inventory: |
            [all]
            localhost
          options: |
            --syntax-check

      - uses: docker-practice/actions-setup-docker@master
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          project: ${{ matrix.projects }}

      - name: Install dependencies for project
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r yourbtc-ansible/${{ matrix.project }}/molecule/requirements.txt
        with:
          project: ${{ matrix.projects }}

      - name: Test with molecule project
        run: |
          cd yourbtc-ansible/${{ matrix.project }}
          molecule test
        with:
          project: ${{ matrix.projects }}
