---
on:
  push:
    paths:
      - '.github/workflows/ansible.yml'
      - 'yourbtc-ansible/**'

jobs:

  check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Check Ansible role syntax
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          playbook: playbook.yml
          directory: ./yourbtc-ansible
          inventory: |
            [all]
            localhost
          options: |
            --syntax-check

  molecule:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8 ]
        project: [ bitcoin-role ]
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies for project
        run: |
          pip3 install install ansible molecule[lint] molecule-docker

      - name: Test with molecule
        run: |
          cd yourbtc-ansible/${{ matrix.project }}
          molecule test
