---
name: Ansible roles
on:
  push:
    paths:
      - '.github/workflows/ansible.yml'
      - 'ansible/**'
      - '!ansible/**/README.md'

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Ansible role syntax
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          playbook: playbook.yml
          directory: ./installer
          inventory: |
            [all]
            localhost
          options: |
            --syntax-check

  molecule:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.8 ]
        project: [ bitcoin-role, lnd-role ]
    steps:
      - uses: actions/checkout@v2
      - uses: docker-practice/actions-setup-docker@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies for project
        run: |
          pip3 install ansible molecule[docker] docker

      - name: Test with molecule
        run: |
          cd ansible/${{ matrix.project }}
          molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
